minor cleanup
prepare for multi-member build

maintenance

no longer ignore Cargo.lock

first draft, implementation is in connection.rs

1st revision, incomplete, still need to move connection into another module

connection renamed to fusion and is now a trait, with CF & KF as its implementations

ignore Cargo.lock, remove conflicting rust settings

enable opencv again

cleanup code

Fusion moved to lib

remove c_f

fix sensor_fusion.rs

update comments

fix a bug in sensor_fusion.rs that doesn't update

add before.sh that open device permission

Connection singleton now rely on OnceLock instead of const

add an example for connection

disable opencv, add cdylib target

add a dummy glasses that always report 0

fix several bugs affecting connection singleton

dummy acc reading now has gravity

add a dummy function and a dummy glasses for testing

draft, get a stable pointer of Euler now

improve Connection interface

simplify any_glasses

minor refactoring

disable grav in cf

Fusion.attitude_euler splitted into rad & degree

gyro speed scaled using microseconds instead of milliseconds

improve data printing in 2 examples

add inconsistency with decay to CF

fix bugs caused by inconsistencies between RUB & FRD frame

"can't find" message now give reasons

disable dummy glasses

list all hid devices in before.sh

before.sh moved to root

add mag reading, not tested

improve before.sh

enable acc in sensor fusion

fusion under connection is now thread safe using Arc<Mutex

fusion is updated by an event loop in a different thread upon starting

connection singleton now uses OnceLock instead of mutex

prepare for lock-free connection impl

type alias for read-write(rw)

impl rw_acquire

fusion & terminating splitted into 2 rw

enable interrupting to let read_fusion having higher priority

terminating & interrupting switch to atomicBool.

TODO: busy-wait should be gone

remove an unsafe

CF for acc is now fully functional

sensor_fusion now prints Quaternion

disable a println

add quaternion API

remove dummy API

revise Connection to allow repeated stop and start

CONNECTION is now an unsafe static mut

Connection now uses RAII pattern

error: cannot assign to `self.attitude` because it is borrowed

add a dummy function to demonstrate

doctest added

add renormalize_fast

demonstrating the error

INCOMPLETE, add test code for the nalgebra bug

all components of naive_cf are now tested, working after 15 minutes

revert println in sensor_fusion.rs

upgrade hidapi

added FusionWithOffset

refactoring, remove FusionWithOffset

minor cleanup

prepare for multi-member build

maintenance

no longer ignore Cargo.lock

first draft, implementation is in connection.rs

1st revision, incomplete, still need to move connection into another module

connection renamed to fusion and is now a trait, with CF & KF as its implementations

ignore Cargo.lock, remove conflicting rust settings

enable opencv again

cleanup code

Fusion moved to lib

remove c_f

fix sensor_fusion.rs

update comments

fix a bug in sensor_fusion.rs that doesn't update

add before.sh that open device permission

Connection singleton now rely on OnceLock instead of const

add an example for connection

disable opencv, add cdylib target

add a dummy glasses that always report 0

fix several bugs affecting connection singleton

dummy acc reading now has gravity

add a dummy function and a dummy glasses for testing

draft, get a stable pointer of Euler now

improve Connection interface

simplify any_glasses

minor refactoring

disable grav in cf

Fusion.attitude_euler splitted into rad & degree

gyro speed scaled using microseconds instead of milliseconds

improve data printing in 2 examples

add inconsistency with decay to CF

fix bugs caused by inconsistencies between RUB & FRD frame

"can't find" message now give reasons

disable dummy glasses

list all hid devices in before.sh

before.sh moved to root

add mag reading, not tested

improve before.sh

enable acc in sensor fusion

fusion under connection is now thread safe using Arc<Mutex

fusion is updated by an event loop in a different thread upon starting

connection singleton now uses OnceLock instead of mutex

prepare for lock-free connection impl

type alias for read-write(rw)

impl rw_acquire

fusion & terminating splitted into 2 rw

enable interrupting to let read_fusion having higher priority

terminating & interrupting switch to atomicBool.

TODO: busy-wait should be gone

remove an unsafe

CF for acc is now fully functional

sensor_fusion now prints Quaternion

disable a println

add quaternion API

remove dummy API

revise Connection to allow repeated stop and start

CONNECTION is now an unsafe static mut

Connection now uses RAII pattern

error: cannot assign to `self.attitude` because it is borrowed

add a dummy function to demonstrate

doctest added

add renormalize_fast

demonstrating the error

INCOMPLETE, add test code for the nalgebra bug

all components of naive_cf are now tested, working after 15 minutes

revert println in sensor_fusion.rs

upgrade hidapi

added FusionWithOffset